# -*- coding: utf-8 -*-
"""Dever-03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lqPrS_KtebU-PgPV2_76g600LuzE78xR
"""

#Importar os módulos do sistema operacional

import os
import locale

#Instalar pt_BR

!/usr/share/locales/install-language-pack pt_BR
!dpkg-reconfigure locales pt_BR

#Reiniciar o processo Python

os.kill(os.getpid(), 9)

import csv

# Função para ler o arquivo CSV e retornar os dados em uma lista
def ler_dados_csv():
    lista_dados = []
    with open("dados.csv", mode="r", encoding="utf-8") as arquivo:
        leitor = csv.reader(arquivo)
        next(leitor)  # Pular o cabeçalho (Nome, Idade)
        for linha in leitor:
            lista_dados.append([linha[0], int(linha[1])])  # Armazenar nome e idade (convertida para int)
    return lista_dados

# Função para encontrar a idade máxima (pessoa mais velha)
def encontrar_idade_maxima(lista_dados):
    idades = [pessoa[1] for pessoa in lista_dados]
    return max(idades)

# Função para validar a resposta do usuário (sim/não)
def validar_resposta(resposta):
    return resposta.strip().lower() in ["sim", "não"]

# Função principal
def main():
    # Ler os dados do arquivo CSV
    lista_dados = ler_dados_csv()
    idade_maxima = encontrar_idade_maxima(lista_dados)

    # Exibir a lista de nomes e idades
    print("\nTítulo: Lista de Nomes")
    print("=" * 30)
    for pessoa in lista_dados:
        print(f"{pessoa[0]} - {pessoa[1]} anos")
    print("=" * 30)

    while True:
        # Solicitar o nome ao usuário
        nome_usuario = input("\nDigite um nome: ")

        # Verificar se o nome está na lista
        encontrado = False
        for pessoa in lista_dados:
            if pessoa[0].lower() == nome_usuario.lower():  # Comparação case-insensitive
                encontrado = True
                nome, idade = pessoa
                if idade == idade_maxima:
                    print(f"{nome} tem {idade} anos e é a pessoa mais velha da lista.")
                else:
                    print(f"{nome} tem {idade} anos, não é a pessoa mais velha da lista.")
                break

        # Caso o nome não seja encontrado
        if not encontrado:
            print("Nome não encontrado.")

        # Perguntar se o usuário deseja continuar (com validação)
        while True:
            continuar = input("\nDeseja fazer uma nova pesquisa? (sim/não): ").strip().lower()
            if validar_resposta(continuar):  # Verifica se a resposta é "sim" ou "não"
                break
            else:
                print("Digite apenas sim ou não.")

        # Encerrar o programa se a resposta for "não"
        if continuar == "não":
            print("Encerrando o programa...")
            break

# Executar o programa
if __name__ == "__main__":
    main()