# -*- coding: utf-8 -*-
"""Dever-07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1az0uodvJWqhARce56RF-b3kft7_2ct5u
"""

#Importar os módulos do sistema operacional

import os
import locale

#Instalar pt_BR

!/usr/share/locales/install-language-pack pt_BR
!dpkg-reconfigure locales pt_BR

#Reiniciar o processo Python

os.kill(os.getpid(), 9)

# Importando as bibliotecas necessárias
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Carregando o dataset Iris
iris = load_iris()
X = iris.data
y = iris.target

# Dividindo os dados - 40% treino, 60% teste
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.4, random_state=42)

# Exibindo a quantidade de itens no conjunto de teste
print("Quantidade de amostras no conjunto de teste:", len(X_test))